### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by AmyMoriyama** [HardenedSteel/I2P.cfg#1]
I followed the instructions here:
https://github.com/HardenedSteel/I2P.cfg#installation

and http still redirects to https and .i2p domains that don't get redirected to https get searched for via duckduckgo.

cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

The only difference I can see is on the instructions, it says:
Download [I2P.cfg](https://github.com/HardenedSteel/I2P.cfg/blob/main/I2P.cfg) and put it in /Data/xxxxxxxx.profilename

but at least on my end, the only browser profile is xxxxxxxx.default-release

EDIT: I just noticed also the instructions say:
Download [config.js](https://github.com/HardenedSteel/I2P.cfg/blob/main/autoconfig.js) and put it in /Browser/defaults/pref
but the filename in the link is autoconfig.js

**Comment by HardenedSteel** [comment]
Sorry, I fixed up the instructions.

Yes, you should put the autoconfig.js file in the `/Browser/defaults/pref` folder then put the I2P.cfg file in your `xxxxxxxx.default-release` folder.

**Comment by AmyMoriyama** [comment]
I already did that once noticed but it doesn't make any difference. The browser acts like it is totally ignoring the config.

**Comment by HardenedSteel** [comment]
Did you try restarting the browser after putting the files?

**Comment by AmyMoriyama** [comment]
Downloaded the browser, extracted, launched once and closed, wget the two raw files to where they are said to be, launch browser, no apparent change in the browser. Restarted the browser once more to be sure, still no apparent changes.

I'm not overly familiar with browser modification or overrides so I can't be all that useful here, but it seems the browser is simply ignoring any overrides.

**Comment by AmyMoriyama** [comment]
So I did some tinkering and this is what I have found so far.

Manually setting everything in about:config works, except the following setting needs to be toggled to false to avoid forcing redirect to https:
dom.security.https_only_mode_pbm

So, it is something to do with the browser ignoring the overrides.

**Comment by HardenedSteel** [comment]
Alright it seems I found the problem, can you follow latest instructions?

**Comment by AmyMoriyama** [comment]
Also wanted to point out I was slightly wrong, it seems network.proxy.type needs to also be set to 1 and maybe network.proxy.no_proxies_on set to 127.0.0.1 but not verified this yet.

So, your new instructions now work, but these two entries need to be added to the I2P.cfg file to make everything work.
lockPref("dom.security.https_only_mode_pbm", false);
lockPref("network.proxy.type", 1);

**Comment by HardenedSteel** [comment]
Added with latest commit, thank you.
